### ISSUE TITLE
Lovely strange error

### ISSUE THREAD

**Issue by LexShadow** [thenullnetwork/chatterbox#3]
`Parse error: syntax error, unexpected end of file.`

Short php is enabled anyway but this is what I get on 5008 what is the last line of the script

**Comment by d-a-s-h-o** [comment]
This is probably due to a simple syntax error when a function from above isn't closed properly... I will check and send the fix soon. Apologies 😁

**Comment by LexShadow** [comment]
> This is probably due to a simple syntax error when a function from above isn't closed properly... I will check and send the fix soon. Apologies 😁
> 
> I will also be releasing another improved script soon after some editing and touch ups which will allow even more customisation and functionality.

That will be great I been trying for a while to find out what as gone funny, I really enjoy your version looked so nice keep working hard.

**Comment by d-a-s-h-o** [comment]
Lol thanks 🙃

**Comment by d-a-s-h-o** [comment]
There... I think I fixed it. There was a missing `}` in line 1905.... Try that new script and let me know.

**Comment by LexShadow** [comment]
I have added the fix to that line and waiting for my bloody tor host to update I will be back with you SOOON as its tested.

**Comment by LexShadow** [comment]
Well that error fixed but 
`Warning: PDO::exec(): SQLSTATE[HY000]: General error: 1 near "CONSTRAINT": syntax error in index.php on line 4315`
lol Maybe I should of downloaded the stable version not the active source lol

**Comment by d-a-s-h-o** [comment]
Lol maybe yeah... hmm that's weird though

**Comment by d-a-s-h-o** [comment]
Try changing ALTER to CREATE

**Comment by LexShadow** [comment]
Just tell me when :)

**Comment by LexShadow** [comment]
I downloaded the stable build that was missing 1905 and I still getting the sqlite error, I should of said I am using sqlite/sqlite3

**Comment by d-a-s-h-o** [comment]
New release fixes this issue.
